# Generated by Django 4.2 on 2023-06-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
