# Generated by Django 4.2 on 2023-06-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_remove_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
